version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: interviewai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
